[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qrdx0s3puwnewu4w5rq4vtve06qvr4xqnhr0xalk076askhsp7rcxxkp5ey"]

[[validator_account]]
address = "tnam1qxtfrw9gqfmejfae96gg2wzztj4mwlch2ssmy78t"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "51.178.74.93:26656"

[validator_account.consensus_key]
pk = "tpknam1qzzjfz2w5ed3qmz6zx2gz263rhppwzhsf0ltnj9l08ek2c6zh3ppsd0xxyp"
authorization = "signam1qraurteluh2wymys23qa8qrcrp68e6fglk67xtzyuq2hc33am6sh4m4wrwetj6rd64ztxa7tn2pqjqhj86ztzk52mv5u96xqsgg89wq2qxxa76"

[validator_account.protocol_key]
pk = "tpknam1qpnccklhqc3fn6n56k9sqvny86fzgwdft6wg49su48augerwrqtkver7uqn"
authorization = "signam1qp0m06lrcky6tgcv7vnqfkxnug22q9u6z8gndj046ft0hxr2u8vhdhfw70atnp467yread6uh53pmel2t2yqna65625rgs5cjknhp7qqkyp5he"

[validator_account.tendermint_node_key]
pk = "tpknam1qzxw4k6kzh94m26mwg4d7v3amu2284wj7r7dypk6rc3xvn2z3pa3g745uwm"
authorization = "signam1qqzstejxm88g88ks4chj0w5s4z42zzxula370aukx59reunszep5sqc0trl0resk5slen7c9ws7lvl3vlkx9p4ylzxqpxx7wk57t2nqzm9c85d"

[validator_account.eth_hot_key]
pk = "tpknam1qyp5l4mmdxffhg3hn0t966sn44jg032sylke8kkq5qd5jkjg5qkjavs3xupwj"
authorization = "signam1qyhkr385mtvaz0j5yvav3j4rg8zfley4xue0sjuccfl29ewlth4v7tey44lvzg7dhezdpraqjprhc5w7cjanpe2jym6u244cm4xf3w4mqqmdt47h"

[validator_account.eth_cold_key]
pk = "tpknam1qypdew23wkxnqkxj40mdyeq6mxfmsws8ql5zqa64kr3qct7un6xv3cspyq8at"
authorization = "signam1q9tms8e609w79qkf4p8h0awz9a37ejtyhjz68hrdnjzlwp5n049vwgemcje5sqvan3fsnrxksqm6hue06urtlmf93ekj2frg5s6j709fqyfdjjcu"

[validator_account.metadata]
email = "it@projectblanc.ch"
website = "https://blanc.group/"
name = "project blanc"

[validator_account.signatures]
tpknam1qrdx0s3puwnewu4w5rq4vtve06qvr4xqnhr0xalk076askhsp7rcxxkp5ey = "signam1qrduw76rqvdem0ut0pj3wllnpsxu0wpk7n0ryenjtzvp9dsmjga6eyqyhz59dt9cel4l4wekvwc725em5u0707razx77mld803cp46gfcxm8s4"
